/**
 * Sofia Platform Catalog — 103 platforms with auth, signals & integration info
 * Source: docs/prompt/sofia_platforms_full.xlsx
 * Single source of truth for platform configurations
 */

import type {
  PlatformConfig,
  IntegrationPhase,
  SignalConfidence,
} from "../types/reputation"

export const PLATFORM_CATALOG: PlatformConfig[] = [
  // =========================================================================
  // DEVELOPPEMENT (17 plateformes)
  // =========================================================================
  {
    id: "github",
    name: "GitHub",
    icon: "github",
    color: "#4472C4",
    authType: "oauth2",
    apiBaseUrl: "https://api.github.com",
    scopes: ["read:user", "repo"],
    dataPoints: [
      "commits",
      "streak",
      "repos",
      "langages",
      "PRs",
      "stars",
      "contributions",
    ],
    targetDomains: ["tech-dev", "entrepreneurship"],
    targetNiches: [
      "frontend",
      "backend",
      "fullstack",
      "ai-research",
      "applied-ai",
      "devops-cloud",
      "oss-contributor",
      "oss-maintainer",
      "smart-contracts",
      "indie-hacking",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    rateLimitInfo: "5000 req/h authenticated",
    notes:
      "API publique pour profils publics. Scope read:user pour donnees privees.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    icon: "gitlab",
    color: "#FC6D26",
    authType: "oauth2",
    apiBaseUrl: "https://gitlab.com/api/v4",
    scopes: ["read_api"],
    dataPoints: [
      "commits",
      "pipelines",
      "merge-requests",
      "issues",
      "activite-projets",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: [
      "backend",
      "devops-cloud",
      "cicd-gitops",
      "oss-contributor",
    ],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Similaire GitHub. Fort signal DevOps. Bonne alternative pour devs enterprise.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    icon: "bitbucket",
    color: "#0052CC",
    authType: "oauth2",
    apiBaseUrl: "https://api.bitbucket.org/2.0",
    dataPoints: ["repos", "commits", "PRs", "pipelines"],
    targetDomains: ["tech-dev"],
    targetNiches: ["backend", "fullstack", "cicd-gitops"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Moins utilise que GitHub mais signal valide, surtout en entreprise.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    icon: "stackoverflow",
    color: "#F48024",
    authType: "oauth2",
    apiBaseUrl: "https://api.stackexchange.com/2.3",
    dataPoints: [
      "reputation",
      "badges",
      "reponses-acceptees",
      "tags-dominants",
      "ratio-ask-answer",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: [
      "frontend",
      "backend",
      "fullstack",
      "ai-research",
      "applied-ai",
      "kubernetes-docker",
      "cybersecurity",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    rateLimitInfo: "25000 req/jour",
    notes:
      "Tags = specialisation exacte. Un des meilleurs signaux dev.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    icon: "huggingface",
    color: "#FFD21E",
    authType: "oauth2",
    apiBaseUrl: "https://huggingface.co/api",
    dataPoints: [
      "modeles-publies",
      "datasets",
      "spaces",
      "downloads",
      "likes",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: [
      "ai-research",
      "applied-ai",
      "mlops",
      "prompt-engineering",
    ],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "API publique. Signal AI/ML irrefutable.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "kaggle",
    name: "Kaggle",
    icon: "kaggle",
    color: "#20BEFF",
    authType: "oauth2",
    apiBaseUrl: "https://www.kaggle.com/api/v1",
    dataPoints: [
      "competitions",
      "medailles",
      "notebooks",
      "datasets",
      "rang",
    ],
    targetDomains: ["tech-dev", "science"],
    targetNiches: [
      "ai-research",
      "applied-ai",
      "applied-math",
    ],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Medailles = validation communaute. Signal recrutement ML fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "npm",
    name: "npm Registry",
    icon: "npm",
    color: "#CB3837",
    authType: "public",
    apiBaseUrl: "https://registry.npmjs.org",
    dataPoints: [
      "packages-publies",
      "telechargements",
      "dependants",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: ["frontend", "backend", "fullstack"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Entierement public. Telechargements hebdo = usage reel.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "pypi",
    name: "PyPI",
    icon: "python",
    color: "#3775A9",
    authType: "public",
    apiBaseUrl: "https://pypi.org/pypi",
    dataPoints: [
      "packages-publies",
      "downloads",
      "versions",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: ["backend", "ai-research", "applied-ai"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "pypistats.org API. Meme logique npm.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "replit",
    name: "Replit",
    icon: "replit",
    color: "#F26207",
    authType: "oauth2",
    apiBaseUrl: "https://replit.com/api",
    dataPoints: [
      "projets-crees",
      "forks",
      "runs",
      "projets-publics",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: ["frontend", "fullstack", "lowcode-nocode"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Bon signal pour apprenants et devs juniors.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "devto",
    name: "Dev.to",
    icon: "devto",
    color: "#0A0A0A",
    authType: "oauth2",
    apiBaseUrl: "https://dev.to/api",
    dataPoints: [
      "articles-publies",
      "reactions",
      "commentaires",
      "tags",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: [
      "frontend",
      "backend",
      "oss-contributor",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "API ouverte. Tags des articles = specialisation precise.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "hashnode",
    name: "Hashnode",
    icon: "hashnode",
    color: "#2962FF",
    authType: "oauth2",
    apiBaseUrl: "https://gql.hashnode.com",
    dataPoints: [
      "articles",
      "tags",
      "followers",
      "reactions",
      "series",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: [
      "frontend",
      "backend",
      "oss-contributor",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "GraphQL API complete. Alternative Dev.to.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    icon: "hackernews",
    color: "#FF6600",
    authType: "public",
    apiBaseUrl: "https://hacker-news.firebaseio.com/v0",
    dataPoints: [
      "points",
      "commentaires",
      "stories-soumises",
      "karma",
    ],
    targetDomains: ["tech-dev", "entrepreneurship"],
    targetNiches: [
      "fullstack",
      "indie-hacking",
      "vc-startup",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Pas d'OAuth. API Firebase publique. Karma = signal qualite.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "leetcode",
    name: "LeetCode",
    icon: "leetcode",
    color: "#FFA116",
    authType: "public",
    apiBaseUrl: "https://leetcode.com/graphql",
    dataPoints: [
      "problemes-resolus",
      "streak",
      "rang",
      "difficulte-hard-medium-easy",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: ["frontend", "backend", "fullstack"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Endpoint GraphQL non officiel mais stable. Signal recrutement top.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "hackerrank",
    name: "HackerRank",
    icon: "hackerrank",
    color: "#00EA64",
    authType: "oauth2",
    apiBaseUrl: "https://www.hackerrank.com/rest",
    dataPoints: [
      "certifications",
      "badges",
      "scores-par-domaine",
      "classement",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: ["frontend", "backend", "fullstack"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Certifications verifiables = signal fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "vercel",
    name: "Vercel",
    icon: "vercel",
    color: "#000000",
    authType: "oauth2",
    apiBaseUrl: "https://api.vercel.com",
    dataPoints: [
      "projets-deployes",
      "frequence-deploiement",
      "frameworks",
      "domaines-custom",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: [
      "frontend",
      "fullstack",
      "serverless-edge",
    ],
    signalConfidence: "high",
    integrationPhase: 2,
    notes: "Signal fort devs frontend actifs.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "netlify",
    name: "Netlify",
    icon: "netlify",
    color: "#00C7B7",
    authType: "oauth2",
    apiBaseUrl: "https://api.netlify.com/api/v1",
    dataPoints: [
      "sites-deployes",
      "builds",
      "formulaires",
      "fonctions",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: ["frontend", "fullstack"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Similaire Vercel.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "codepen",
    name: "CodePen",
    icon: "codepen",
    color: "#1E1F26",
    authType: "oauth2",
    apiBaseUrl: "https://cpv2api.com",
    dataPoints: [
      "pens-publies",
      "forks-recus",
      "likes",
      "collections",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: ["frontend"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Signal designers-developers (CSS art, animations).",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // DESIGN (10 plateformes)
  // =========================================================================
  {
    id: "figma",
    name: "Figma",
    icon: "figma",
    color: "#F24E1E",
    authType: "oauth2",
    apiBaseUrl: "https://api.figma.com/v1",
    scopes: ["files:read"],
    dataPoints: [
      "projets",
      "fichiers-edites",
      "commentaires",
      "collaborateurs",
      "plugins",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "product-design",
      "design-system",
      "prototyping",
      "ui-ux-design",
    ],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Meilleur signal design produit disponible.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "behance",
    name: "Behance",
    icon: "behance",
    color: "#1769FF",
    authType: "oauth2",
    apiBaseUrl: "https://api.behance.net/v2",
    dataPoints: [
      "projets-publies",
      "appreciations",
      "vues",
      "followers",
      "categories",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "concept-art",
      "character-design",
      "branding",
      "graphic-design",
    ],
    signalConfidence: "high",
    integrationPhase: 2,
    notes:
      "API Adobe. Categories = specialisation precise.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "dribbble",
    name: "Dribbble",
    icon: "dribbble",
    color: "#EA4C89",
    authType: "oauth2",
    apiBaseUrl: "https://api.dribbble.com/v2",
    dataPoints: [
      "shots-postes",
      "likes",
      "followers",
      "rebounds",
      "pro-account",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "product-design",
      "ui-ux-design",
      "concept-art",
    ],
    signalConfidence: "high",
    integrationPhase: 2,
    notes: "Signal design digital qualitatif.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "deviantart",
    name: "DeviantArt",
    icon: "deviantart",
    color: "#00E59B",
    authType: "oauth2",
    apiBaseUrl: "https://www.deviantart.com/api/v1/oauth2",
    dataPoints: [
      "deviations",
      "faves",
      "commentaires",
      "watchers",
      "galeries",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "concept-art",
      "character-design",
      "pixel-art",
      "generative-art",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "API bien documentee. Large communaute illustration/fan art.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "sketchfab",
    name: "Sketchfab",
    icon: "sketchfab",
    color: "#1CAAD9",
    authType: "oauth2",
    apiBaseUrl: "https://api.sketchfab.com/v3",
    dataPoints: [
      "modeles-3d",
      "vues",
      "likes",
      "followers",
      "categories",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "blender",
      "cinema4d-maya",
      "game-assets",
      "architecture-3d",
    ],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "Excellent signal 3D artists.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "unsplash",
    name: "Unsplash",
    icon: "unsplash",
    color: "#000000",
    authType: "oauth2",
    apiBaseUrl: "https://api.unsplash.com",
    dataPoints: [
      "photos-uploadees",
      "telechargements",
      "vues",
      "collections",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "portrait-photo",
      "landscape-photo",
      "street-photo",
      "studio-product",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    rateLimitInfo: "50 req/h",
    notes:
      "Telechargements = usage reel = qualite prouvee.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "flickr",
    name: "Flickr",
    icon: "flickr",
    color: "#0063DC",
    authType: "oauth1",
    apiBaseUrl: "https://api.flickr.com/services/rest",
    dataPoints: [
      "photos-publiees",
      "vues",
      "faves",
      "groupes",
      "tags-exif",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "portrait-photo",
      "landscape-photo",
      "street-photo",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "EXIF data = type d'appareil = niveau de serieux.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "500px",
    name: "500px",
    icon: "500px",
    color: "#0099E5",
    authType: "oauth2",
    apiBaseUrl: "https://api.500px.com/v1",
    dataPoints: [
      "photos",
      "pulse-score",
      "affections",
      "vues",
      "categories",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "portrait-photo",
      "landscape-photo",
      "street-photo",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Pulse = score qualite automatique. Photographes serieux.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "itchio",
    name: "Itch.io",
    icon: "itchio",
    color: "#FA5C5C",
    authType: "api_key",
    apiBaseUrl: "https://itch.io/api/1",
    dataPoints: [
      "jeux-publies",
      "downloads",
      "ratings",
      "revenus",
    ],
    targetDomains: ["design-creative", "gaming"],
    targetNiches: [
      "pixel-art",
      "pixel-indie",
      "game-jams",
      "game-assets",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Signal game designers et artistes pixel/indie.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "wattpad",
    name: "Wattpad",
    icon: "wattpad",
    color: "#FF6122",
    authType: "oauth2",
    apiBaseUrl: "https://api.wattpad.com/v4",
    dataPoints: [
      "histoires-publiees",
      "lectures",
      "votes",
      "followers",
      "genres",
    ],
    targetDomains: ["design-creative", "literature"],
    targetNiches: [
      "novel-short-story",
      "creative-writing",
      "worldbuilding",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal auteurs fiction.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // MUSIQUE (9 plateformes)
  // =========================================================================
  {
    id: "spotify",
    name: "Spotify",
    icon: "spotify",
    color: "#1DB954",
    authType: "oauth2",
    authUrl: "https://accounts.spotify.com/authorize",
    tokenUrl: "https://accounts.spotify.com/api/token",
    apiBaseUrl: "https://api.spotify.com/v1",
    scopes: [
      "user-read-private",
      "user-top-read",
      "user-follow-read",
      "playlist-read-private",
    ],
    dataPoints: [
      "top-artists",
      "top-tracks",
      "genres",
      "playlists-creees",
      "podcasts",
    ],
    targetDomains: ["music-audio"],
    targetNiches: [
      "beatmaking",
      "electronic-production",
      "psytrance-goa",
      "techno-industrial",
      "house-disco",
      "curation-playlisting",
    ],
    signalConfidence: "medium",
    integrationPhase: 0,
    notes:
      "Signal d'interet mais pas d'expertise. Combiner avec creation.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "lastfm",
    name: "Last.fm",
    icon: "lastfm",
    color: "#D51007",
    authType: "oauth2",
    apiBaseUrl: "https://ws.audioscrobbler.com/2.0",
    dataPoints: [
      "scrobbles-totaux",
      "artistes-top",
      "tags",
      "loved-tracks",
      "anciennete",
    ],
    targetDomains: ["music-audio"],
    targetNiches: [
      "beatmaking",
      "electronic-production",
      "psytrance-goa",
      "techno-industrial",
      "house-disco",
      "vinyl-collecting",
      "genre-history",
    ],
    signalConfidence: "high",
    integrationPhase: 1,
    notes:
      "Historique long = passion durable. Tags = niche precise.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    icon: "soundcloud",
    color: "#FF5500",
    authType: "oauth2",
    apiBaseUrl: "https://api.soundcloud.com",
    dataPoints: [
      "tracks-uploadees",
      "plays",
      "reposts",
      "commentaires",
      "followers",
      "sets",
    ],
    targetDomains: ["music-audio"],
    targetNiches: [
      "beatmaking",
      "electronic-production",
      "sampling-crates",
      "mixing-mastering",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "Signal musiciens et DJs actifs. API bien maintenue.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "mixcloud",
    name: "Mixcloud",
    icon: "mixcloud",
    color: "#5000FF",
    authType: "oauth2",
    apiBaseUrl: "https://api.mixcloud.com",
    dataPoints: [
      "mixes-uploades",
      "ecoutes",
      "followers",
      "duree",
      "genres-tagues",
    ],
    targetDomains: ["music-audio"],
    targetNiches: [
      "psytrance-goa",
      "techno-industrial",
      "house-disco",
      "dnb-jungle",
      "hiphop-turntablism",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes: "Excellent pour valider expertise DJ/radio.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "deezer",
    name: "Deezer",
    icon: "deezer",
    color: "#00C7F2",
    authType: "oauth2",
    apiBaseUrl: "https://api.deezer.com",
    dataPoints: [
      "playlists",
      "artistes-favoris",
      "albums",
      "historique",
      "genres",
    ],
    targetDomains: ["music-audio"],
    targetNiches: [
      "curation-playlisting",
      "genre-history",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Moins riche que Spotify mais API plus ouverte.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "discogs",
    name: "Discogs",
    icon: "discogs",
    color: "#333333",
    authType: "oauth1",
    apiBaseUrl: "https://api.discogs.com",
    dataPoints: [
      "collection-vinyles",
      "ventes",
      "want-list",
      "genres-collectes",
    ],
    targetDomains: ["music-audio", "food-lifestyle"],
    targetNiches: [
      "vinyl-collecting",
      "cassette-collecting",
      "psytrance-goa",
      "techno-industrial",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "Signal collector/crate digger ultra-precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "listenbrainz",
    name: "ListenBrainz",
    icon: "listenbrainz",
    color: "#353070",
    authType: "oauth2",
    apiBaseUrl: "https://api.listenbrainz.org",
    dataPoints: [
      "scrobbles",
      "artistes",
      "releases",
      "statistiques-temporelles",
    ],
    targetDomains: ["music-audio"],
    targetNiches: [
      "vinyl-collecting",
      "genre-history",
      "curation-playlisting",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Alternative open source Last.fm. Donnees completes.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "musicbrainz",
    name: "MusicBrainz",
    icon: "musicbrainz",
    color: "#BA478F",
    authType: "oauth2",
    apiBaseUrl: "https://musicbrainz.org/ws/2",
    dataPoints: [
      "contributions-editoriales",
      "artistes-ajoutes",
      "albums",
      "labels",
    ],
    targetDomains: ["music-audio"],
    targetNiches: [
      "music-journalism",
      "genre-history",
      "curation-playlisting",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Contributeur = passionne encyclopediste.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "bandcamp",
    name: "Bandcamp",
    icon: "bandcamp",
    color: "#1DA0C3",
    authType: "none",
    dataPoints: [
      "albums",
      "tracks",
      "ventes",
      "fans",
      "wishlistes",
      "genres",
    ],
    targetDomains: ["music-audio"],
    targetNiches: [
      "beatmaking",
      "electronic-production",
      "vinyl-collecting",
    ],
    signalConfidence: "very_high",
    integrationPhase: 4,
    notes:
      "Pas d'OAuth officiel. Donnees partiellement publiques.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // GAMING (12 plateformes)
  // =========================================================================
  {
    id: "steam",
    name: "Steam",
    icon: "steam",
    color: "#1B2838",
    authType: "oauth2",
    apiBaseUrl: "https://api.steampowered.com",
    dataPoints: [
      "heures-par-jeu",
      "achievements",
      "jeux-possedes",
      "reviews",
      "groupes",
    ],
    targetDomains: ["gaming"],
    targetNiches: [
      "valorant-csgo",
      "action-rpg",
      "grand-strategy",
      "mmo-social",
      "retro-collecting",
    ],
    signalConfidence: "high",
    integrationPhase: 2,
    notes:
      "API publique. Heures de jeu = signal engagement fort.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "chess-com",
    name: "Chess.com",
    icon: "chess",
    color: "#769656",
    authType: "public",
    apiBaseUrl: "https://api.chess.com/pub",
    dataPoints: [
      "elo",
      "parties-jour",
      "streak",
      "openings",
      "tournois",
      "puzzles",
    ],
    targetDomains: ["gaming", "sport-health"],
    targetNiches: ["chess", "go-shogi"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "100% public sans OAuth. Elo = metrique universelle de skill.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "lichess",
    name: "Lichess",
    icon: "lichess",
    color: "#000000",
    authType: "oauth2",
    apiBaseUrl: "https://lichess.org/api",
    dataPoints: [
      "elo",
      "parties",
      "ouvertures",
      "puzzles",
      "tournois",
      "streak",
    ],
    targetDomains: ["gaming"],
    targetNiches: ["chess"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "Open source, API complete, donnees riches.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "riot-games",
    name: "Riot Games API",
    icon: "riot",
    color: "#D32936",
    authType: "oauth2",
    apiBaseUrl: "https://euw1.api.riotgames.com",
    dataPoints: [
      "rang",
      "kda",
      "champions-joues",
      "win-rate",
      "heures",
    ],
    targetDomains: ["gaming"],
    targetNiches: [
      "valorant-csgo",
      "fps-competitive",
    ],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "API officielle. Rang = niveau precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "blizzard",
    name: "Blizzard API",
    icon: "blizzard",
    color: "#00AEFF",
    authType: "oauth2",
    apiBaseUrl: "https://eu.api.blizzard.com",
    dataPoints: [
      "personnages",
      "achievements",
      "item-level",
      "classements",
    ],
    targetDomains: ["gaming"],
    targetNiches: ["wow", "ffxiv", "overwatch"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "WoW = signal MMO fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "opendota",
    name: "OpenDota",
    icon: "opendota",
    color: "#6A7C8B",
    authType: "public",
    apiBaseUrl: "https://api.opendota.com/api",
    dataPoints: [
      "heros-joues",
      "win-rate",
      "gpm",
      "tournois",
      "comportement",
    ],
    targetDomains: ["gaming"],
    targetNiches: ["rts-starcraft"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "Entierement public. Donnees precises.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "tracker-gg",
    name: "Tracker.gg",
    icon: "trackergg",
    color: "#1D9BF0",
    authType: "api_key",
    apiBaseUrl: "https://public-api.tracker.gg/v2",
    dataPoints: [
      "stats-multi-jeux",
      "rang",
      "kda",
      "win-rate",
    ],
    targetDomains: ["gaming"],
    targetNiches: [
      "valorant-csgo",
      "apex-warzone",
      "rainbow-six",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Agregateur stats gaming multi-titres.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "boardgamegeek",
    name: "BoardGameGeek",
    icon: "boardgamegeek",
    color: "#FF5100",
    authType: "public",
    apiBaseUrl: "https://boardgamegeek.com/xmlapi2",
    dataPoints: [
      "collection",
      "parties-jouees",
      "ratings",
      "listes",
    ],
    targetDomains: ["gaming"],
    targetNiches: ["board-games", "puzzles"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "API XML ancienne mais stable et complete.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "myanimelist",
    name: "MyAnimeList",
    icon: "myanimelist",
    color: "#2E51A2",
    authType: "oauth2",
    apiBaseUrl: "https://api.myanimelist.net/v2",
    dataPoints: [
      "anime-vus",
      "scores",
      "liste",
      "genres",
      "studios",
    ],
    targetDomains: ["gaming", "video-cinema"],
    targetNiches: ["anime", "manga-comics"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal otaku/weeb precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "anilist",
    name: "AniList",
    icon: "anilist",
    color: "#02A9FF",
    authType: "oauth2",
    apiBaseUrl: "https://graphql.anilist.co",
    dataPoints: [
      "anime",
      "manga",
      "scores",
      "activite",
      "favoris",
      "genres",
    ],
    targetDomains: ["gaming", "video-cinema"],
    targetNiches: ["anime", "manga-comics"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "GraphQL complete. Alternative MAL moderne.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "trakt",
    name: "Trakt.tv",
    icon: "trakt",
    color: "#ED1C24",
    authType: "oauth2",
    apiBaseUrl: "https://api.trakt.tv",
    dataPoints: [
      "films-vus",
      "series-vues",
      "ratings",
      "listes",
      "historique",
    ],
    targetDomains: ["gaming", "video-cinema", "literature"],
    targetNiches: [
      "arthouse",
      "scifi-fantasy-film",
      "prestige-tv",
      "anime",
    ],
    signalConfidence: "high",
    integrationPhase: 2,
    notes: "Scrobbling films/series. Signal cinephile.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "rawg",
    name: "RAWG",
    icon: "rawg",
    color: "#1C1C1C",
    authType: "api_key",
    apiBaseUrl: "https://api.rawg.io/api",
    dataPoints: [
      "bibliotheque-jeux",
      "ratings",
      "plateformes",
      "genres",
    ],
    targetDomains: ["gaming"],
    targetNiches: [
      "action-rpg",
      "fps-competitive",
      "indie-art-games",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Base de donnees jeux + collection user.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // WEB3 (10 plateformes)
  // =========================================================================
  {
    id: "wallet-siwe",
    name: "Wallet ETH/Base/Arb",
    icon: "ethereum",
    color: "#627EEA",
    authType: "siwe",
    dataPoints: [
      "transactions",
      "protocoles-interagis",
      "anciennete",
      "volume",
      "nfts",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "yield-farming",
      "lending",
      "dex-amm",
      "nft-collecting",
      "nft-creation",
      "smart-contracts",
      "dao-voting",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Verite absolue on-chain. Alchemy free 300M compute units/mois.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "lens",
    name: "Lens Protocol",
    icon: "lens",
    color: "#ABFE2C",
    authType: "siwe",
    apiBaseUrl: "https://api-v2.lens.dev",
    dataPoints: [
      "posts",
      "follows",
      "mirrors",
      "collects",
      "profil",
      "communautes",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "lens-protocol",
      "socialfi",
      "web3-social",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "API GraphQL publique. Signal DeSo early adopter.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "farcaster",
    name: "Farcaster / Neynar",
    icon: "farcaster",
    color: "#8A63D2",
    authType: "siwf",
    apiBaseUrl: "https://api.neynar.com/v2/farcaster",
    dataPoints: [
      "casts",
      "likes",
      "follows",
      "channels",
      "anciennete",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "farcaster-warpcast",
      "socialfi",
      "web3-social",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "API Neynar. Signal web3 social natif.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "ens",
    name: "ENS (Ethereum Name Service)",
    icon: "ens",
    color: "#5298FF",
    authType: "public",
    dataPoints: [
      "ens-possede",
      "sous-domaines",
      "date-mint",
      "text-records",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "self-custody",
      "btc-only",
      "web3-social",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Lookup on-chain. ENS = identite stable = +15 pts.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "the-graph",
    name: "The Graph",
    icon: "thegraph",
    color: "#6747ED",
    authType: "public",
    dataPoints: [
      "positions-defi",
      "swaps",
      "liquidite",
      "gouvernance-dao",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "yield-farming",
      "lending",
      "dex-amm",
      "dao-voting",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Subgraph par protocole. Donnees on-chain structurees.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "opensea",
    name: "OpenSea",
    icon: "opensea",
    color: "#2081E2",
    authType: "api_key",
    apiBaseUrl: "https://api.opensea.io/api/v2",
    dataPoints: [
      "nfts-possedes",
      "mintes",
      "vendus",
      "collections-creees",
      "volume",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "nft-collecting",
      "nft-creation",
      "generative-nft",
      "pfp-communities",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Distinction createur/collectionneur/trader essentielle.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "zora",
    name: "Zora",
    icon: "zora",
    color: "#5B5BD6",
    authType: "public",
    dataPoints: [
      "nfts-mintes",
      "editions-creees",
      "collectes",
      "revenus",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "nft-creation",
      "generative-nft",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "API ouverte. Signal createur web3 fort.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "mirror",
    name: "Mirror.xyz",
    icon: "mirror",
    color: "#007AFF",
    authType: "public",
    dataPoints: [
      "articles-publies",
      "editions-mintees",
      "abonnes",
    ],
    targetDomains: ["web3-crypto", "literature"],
    targetNiches: [
      "web3-social",
      "substack-newsletter",
      "dao-governance",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal rare : writer web3 natif.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "coinbase",
    name: "Coinbase",
    icon: "coinbase",
    color: "#0052FF",
    authType: "oauth2",
    apiBaseUrl: "https://api.coinbase.com/v2",
    scopes: ["wallet:user:read"],
    dataPoints: [
      "transactions",
      "assets",
      "earn-quizzes",
      "staking",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "yield-farming",
      "self-custody",
      "altcoins-gems",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Coinbase Earn = signal educatif.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "snapshot",
    name: "Snapshot",
    icon: "snapshot",
    color: "#F3B04E",
    authType: "public",
    apiBaseUrl: "https://hub.snapshot.org/graphql",
    dataPoints: [
      "votes-dao",
      "propositions-creees",
      "espaces-suivis",
    ],
    targetDomains: ["web3-crypto"],
    targetNiches: [
      "dao-voting",
      "contributor-dao",
      "grants-funding",
      "token-politics",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "Signal gouvernance DAO ultra-precis.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // SPORT (6 plateformes uniques)
  // =========================================================================
  {
    id: "strava",
    name: "Strava",
    icon: "strava",
    color: "#FC4C02",
    authType: "oauth2",
    authUrl: "https://www.strava.com/oauth/authorize",
    tokenUrl: "https://www.strava.com/oauth/token",
    apiBaseUrl: "https://www.strava.com/api/v3",
    scopes: ["read", "activity:read"],
    dataPoints: [
      "activites",
      "km",
      "sports",
      "records-perso",
      "defis",
      "segments",
    ],
    targetDomains: ["sport-health"],
    targetNiches: [
      "urban-running",
      "short-trail",
      "ultra-trail",
      "cycling-triathlon",
      "swimming",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    rateLimitInfo: "100 req/15min",
    notes:
      "API complete. Donnees GPS precises. Excellent engagement sportif.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "garmin",
    name: "Garmin Connect",
    icon: "garmin",
    color: "#007CC3",
    authType: "oauth2",
    apiBaseUrl: "https://apis.garmin.com",
    dataPoints: [
      "pas",
      "sommeil",
      "vo2max",
      "entrainements",
      "hrv",
      "activites",
    ],
    targetDomains: ["sport-health"],
    targetNiches: [
      "urban-running",
      "cycling-triathlon",
      "running-data",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Donnees sante precises. Signal serieux.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "polar",
    name: "Polar Flow",
    icon: "polar",
    color: "#D40000",
    authType: "oauth2",
    apiBaseUrl: "https://www.polaraccesslink.com/v3",
    dataPoints: [
      "entrainements",
      "frequence-cardiaque",
      "charge",
      "recuperation",
    ],
    targetDomains: ["sport-health"],
    targetNiches: [
      "urban-running",
      "cycling-triathlon",
      "running-data",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Similaire Garmin.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "wahoo",
    name: "Wahoo",
    icon: "wahoo",
    color: "#0068B5",
    authType: "oauth2",
    apiBaseUrl: "https://api.wahooligan.com",
    dataPoints: [
      "activites-cyclisme",
      "puissance",
      "vo2max",
      "entrainements",
    ],
    targetDomains: ["sport-health"],
    targetNiches: ["cycling-triathlon"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal cyclisme/triathlon serieux.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "komoot",
    name: "Komoot",
    icon: "komoot",
    color: "#6AA127",
    authType: "oauth2",
    apiBaseUrl: "https://api.komoot.de/v007",
    dataPoints: [
      "randonnees",
      "tours",
      "highlights",
      "collections",
      "sports",
    ],
    targetDomains: ["sport-health", "nature-environment"],
    targetNiches: [
      "hiking-trek",
      "short-trail",
      "outdoor-climbing",
    ],
    signalConfidence: "high",
    integrationPhase: 2,
    notes:
      "Signal outdoor/nature. Activites geolocalisees.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "fitbit",
    name: "Fitbit",
    icon: "fitbit",
    color: "#00B0B9",
    authType: "oauth2",
    apiBaseUrl: "https://api.fitbit.com/1.2",
    dataPoints: [
      "pas",
      "calories",
      "sommeil",
      "activites",
      "frequence-cardiaque",
    ],
    targetDomains: ["sport-health"],
    targetNiches: [
      "nutrition",
      "yoga-pilates",
      "biohacking-longevity",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal sante quotidienne.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // SOCIAL (6 plateformes)
  // =========================================================================
  {
    id: "reddit",
    name: "Reddit",
    icon: "reddit",
    color: "#FF4500",
    authType: "oauth2",
    authUrl: "https://www.reddit.com/api/v1/authorize",
    tokenUrl: "https://www.reddit.com/api/v1/access_token",
    apiBaseUrl: "https://oauth.reddit.com",
    scopes: ["identity", "read", "mysubreddits"],
    dataPoints: [
      "karma",
      "subreddits-actifs",
      "anciennete",
      "posts-comments",
      "awards",
    ],
    targetDomains: [
      "tech-dev",
      "gaming",
      "science",
      "sport-health",
      "personal-dev",
    ],
    targetNiches: [
      "chess",
      "ai-research",
      "powerlifting",
      "fire",
      "mma-grappling",
      "urban-running",
    ],
    signalConfidence: "high",
    integrationPhase: 1,
    rateLimitInfo: "100 req/min",
    notes:
      "Subreddits = mapping niche ultra-precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "discord",
    name: "Discord",
    icon: "discord",
    color: "#5865F2",
    authType: "oauth2",
    authUrl: "https://discord.com/api/oauth2/authorize",
    tokenUrl: "https://discord.com/api/oauth2/token",
    apiBaseUrl: "https://discord.com/api/v10",
    scopes: ["identify", "guilds"],
    dataPoints: [
      "serveurs-rejoints",
      "roles",
      "anciennete",
    ],
    targetDomains: [
      "tech-dev",
      "gaming",
      "web3-crypto",
      "music-audio",
    ],
    targetNiches: [
      "oss-contributor",
      "wow",
      "lens-protocol",
      "farcaster-warpcast",
    ],
    signalConfidence: "high",
    integrationPhase: 0,
    notes:
      "Serveurs = communautes = domaines. Roles = legitimite.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "mastodon",
    name: "Mastodon",
    icon: "mastodon",
    color: "#6364FF",
    authType: "oauth2",
    dataPoints: [
      "toots",
      "followers",
      "instances",
      "favoris",
    ],
    targetDomains: ["tech-dev"],
    targetNiches: [
      "oss-contributor",
      "oss-maintainer",
      "privacy-opsec",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Instance choisie = signal fort (fosstodon = dev, merveilles = design).",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "bluesky",
    name: "Bluesky",
    icon: "bluesky",
    color: "#0085FF",
    authType: "oauth2",
    apiBaseUrl: "https://bsky.social/xrpc",
    dataPoints: [
      "posts",
      "follows",
      "listes",
      "starter-packs",
    ],
    targetDomains: ["tech-dev", "web3-crypto"],
    targetNiches: [
      "oss-contributor",
      "web3-social",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "AT Protocol ouvert. Starter packs = niches precises.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "tumblr",
    name: "Tumblr",
    icon: "tumblr",
    color: "#001935",
    authType: "oauth1",
    apiBaseUrl: "https://api.tumblr.com/v2",
    dataPoints: [
      "posts",
      "tags",
      "reblogged",
      "followers",
    ],
    targetDomains: ["design-creative"],
    targetNiches: [
      "concept-art",
      "character-design",
      "pixel-art",
    ],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Tags = niches culturelles precises. API maintenue.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "pinterest",
    name: "Pinterest",
    icon: "pinterest",
    color: "#E60023",
    authType: "oauth2",
    apiBaseUrl: "https://api.pinterest.com/v5",
    dataPoints: [
      "boards",
      "pins",
      "categories",
      "followers",
    ],
    targetDomains: ["design-creative", "food-lifestyle"],
    targetNiches: [
      "interior-design",
      "fashion-design",
      "world-cuisine",
    ],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Boards = centres d'interet visuels.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // VIDEO (5 plateformes)
  // =========================================================================
  {
    id: "youtube",
    name: "YouTube",
    icon: "youtube",
    color: "#FF0000",
    authType: "oauth2",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    apiBaseUrl: "https://www.googleapis.com/youtube/v3",
    scopes: [
      "https://www.googleapis.com/auth/youtube.readonly",
    ],
    dataPoints: [
      "videos-uploadees",
      "vues",
      "abonnes",
      "chaines-suivies",
      "commentaires",
    ],
    targetDomains: ["video-cinema"],
    targetNiches: [
      "vlogging",
      "edu-vulgarisation",
      "lets-play",
      "tech-reviews",
    ],
    signalConfidence: "high",
    integrationPhase: 0,
    rateLimitInfo: "10000 unites/jour",
    notes:
      "Donnees createur accessibles. Consommation restreinte.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "twitch",
    name: "Twitch",
    icon: "twitch",
    color: "#9146FF",
    authType: "oauth2",
    authUrl: "https://id.twitch.tv/oauth2/authorize",
    tokenUrl: "https://id.twitch.tv/oauth2/token",
    apiBaseUrl: "https://api.twitch.tv/helix",
    scopes: ["user:read:follows"],
    dataPoints: [
      "heures-streamees",
      "followers",
      "subs",
      "jeux",
      "categories",
      "clips",
    ],
    targetDomains: [
      "video-cinema",
      "gaming",
      "performing-arts",
    ],
    targetNiches: [
      "lets-play",
      "valorant-csgo",
      "classical-theater",
    ],
    signalConfidence: "very_high",
    integrationPhase: 0,
    notes:
      "API Helix complete. Signal createur live fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "vimeo",
    name: "Vimeo",
    icon: "vimeo",
    color: "#1AB7EA",
    authType: "oauth2",
    apiBaseUrl: "https://api.vimeo.com",
    dataPoints: [
      "videos-uploadees",
      "vues",
      "likes",
      "portfolios",
      "collections",
    ],
    targetDomains: ["video-cinema"],
    targetNiches: [
      "indie-cinema",
      "short-film",
      "color-grading",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Signal creatif video plus qualitatif que YouTube.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "dailymotion",
    name: "Dailymotion",
    icon: "dailymotion",
    color: "#00AAFF",
    authType: "oauth2",
    apiBaseUrl: "https://api.dailymotion.com",
    dataPoints: [
      "videos-publiees",
      "vues",
      "abonnes",
      "categories",
    ],
    targetDomains: ["video-cinema"],
    targetNiches: ["vlogging", "edu-vulgarisation"],
    signalConfidence: "medium",
    integrationPhase: 4,
    notes: "Moins riche que YouTube mais API ouverte.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  // Trakt.tv already listed under Gaming

  // =========================================================================
  // SCIENCE & EDUCATION (8 plateformes)
  // =========================================================================
  {
    id: "orcid",
    name: "ORCID",
    icon: "orcid",
    color: "#A6CE39",
    authType: "oauth2",
    apiBaseUrl: "https://pub.orcid.org/v3.0",
    dataPoints: [
      "publications",
      "citations",
      "affiliations",
      "subventions",
      "peer-reviews",
    ],
    targetDomains: ["science"],
    targetNiches: [
      "pure-math",
      "theoretical-physics",
      "molecular-biology",
      "cognitive-neuro",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "Standard mondial academique. Signal irrefutable.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "arxiv",
    name: "ArXiv",
    icon: "arxiv",
    color: "#B31B1B",
    authType: "public",
    apiBaseUrl: "http://export.arxiv.org/api",
    dataPoints: [
      "papiers-soumis",
      "domaines",
      "co-auteurs",
    ],
    targetDomains: ["science", "tech-dev"],
    targetNiches: [
      "ai-research",
      "theoretical-physics",
      "pure-math",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "API publique. Soumission de papier = signal academique.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    icon: "semanticscholar",
    color: "#1857B6",
    authType: "api_key",
    apiBaseUrl: "https://api.semanticscholar.org/graph/v1",
    dataPoints: [
      "publications",
      "citations",
      "co-auteurs",
      "domaines",
    ],
    targetDomains: ["science"],
    targetNiches: [
      "pure-math",
      "theoretical-physics",
      "molecular-biology",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "211M papiers indexes.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "pubmed",
    name: "PubMed",
    icon: "pubmed",
    color: "#326599",
    authType: "public",
    apiBaseUrl: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
    dataPoints: [
      "publications-medicales",
      "citations",
      "mesh-terms",
    ],
    targetDomains: ["science"],
    targetNiches: [
      "molecular-biology",
      "cognitive-neuro",
      "genetics-crispr",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "Signal recherche biomedicale precis.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "openlibrary",
    name: "OpenLibrary",
    icon: "openlibrary",
    color: "#3D6B2E",
    authType: "public",
    apiBaseUrl: "https://openlibrary.org/api",
    dataPoints: [
      "livres-lus",
      "listes",
      "reviews",
      "editions",
    ],
    targetDomains: ["science", "literature"],
    targetNiches: [
      "scifi-dystopia",
      "fantasy-epic",
      "political-essays",
      "pop-science-books",
    ],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Alternative open source Goodreads.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    icon: "wikipedia",
    color: "#000000",
    authType: "public",
    apiBaseUrl: "https://en.wikipedia.org/w/api.php",
    dataPoints: [
      "articles-edites",
      "categories",
      "discussions",
      "anciennete",
    ],
    targetDomains: ["science"],
    targetNiches: [
      "ancient-history",
      "etymology",
      "genre-history",
    ],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Contributions = expertise encodee. Categories = niche.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "duolingo",
    name: "Duolingo",
    icon: "duolingo",
    color: "#58CC02",
    authType: "public",
    dataPoints: [
      "streak",
      "langues",
      "xp",
      "league",
      "lecons",
    ],
    targetDomains: ["science", "personal-dev"],
    targetNiches: [
      "language-learning",
      "meditation-vipassana",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Endpoint non officiel stable. Streak = discipline.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "khan-academy",
    name: "Khan Academy",
    icon: "khanacademy",
    color: "#14BF96",
    authType: "oauth2",
    apiBaseUrl: "https://www.khanacademy.org/api",
    dataPoints: [
      "exercices-completes",
      "cours",
      "badges",
      "progression",
    ],
    targetDomains: ["science"],
    targetNiches: [
      "applied-math",
      "math-olympiads",
      "pop-science-physics",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal apprentissage actif.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // BUSINESS (4 plateformes)
  // =========================================================================
  {
    id: "producthunt",
    name: "Product Hunt",
    icon: "producthunt",
    color: "#DA552F",
    authType: "oauth2",
    apiBaseUrl: "https://api.producthunt.com/v2/api/graphql",
    dataPoints: [
      "produits-lances",
      "upvotes",
      "commentaires",
      "maker-badge",
      "featured",
    ],
    targetDomains: ["entrepreneurship"],
    targetNiches: [
      "indie-hacking",
      "vc-startup",
      "saas-b2b",
      "consumer-apps",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "API GraphQL. Featured = validation forte.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "notion",
    name: "Notion",
    icon: "notion",
    color: "#000000",
    authType: "oauth2",
    apiBaseUrl: "https://api.notion.com/v1",
    dataPoints: [
      "workspaces",
      "templates-publies",
      "integrations",
    ],
    targetDomains: ["entrepreneurship"],
    targetNiches: [
      "second-brain",
      "gtd-agile",
      "time-blocking",
    ],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Signal indirect. Templates = maker/consultant.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "todoist",
    name: "Todoist",
    icon: "todoist",
    color: "#E44332",
    authType: "oauth2",
    apiBaseUrl: "https://api.todoist.com/rest/v2",
    dataPoints: [
      "taches-completees",
      "projets",
      "labels",
      "streaks",
    ],
    targetDomains: ["entrepreneurship", "personal-dev"],
    targetNiches: [
      "gtd-agile",
      "time-blocking",
      "deep-work",
    ],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Signal productivite. Karma = engagement.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "linear",
    name: "Linear",
    icon: "linear",
    color: "#5E6AD2",
    authType: "oauth2",
    apiBaseUrl: "https://api.linear.app/graphql",
    dataPoints: [
      "issues",
      "projets",
      "cycles",
      "equipes",
    ],
    targetDomains: ["entrepreneurship", "tech-dev"],
    targetNiches: [
      "indie-hacking",
      "saas-b2b",
      "cicd-gitops",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal maker/CTO fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // LIFESTYLE (4 plateformes)
  // =========================================================================
  {
    id: "untappd",
    name: "Untappd",
    icon: "untappd",
    color: "#FFC000",
    authType: "oauth2",
    apiBaseUrl: "https://api.untappd.com/v4",
    dataPoints: [
      "bieres-checkees",
      "brasseries",
      "notes",
      "badges",
      "wish-list",
    ],
    targetDomains: ["food-lifestyle"],
    targetNiches: ["craft-beer"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Niche precise. Signal passionne craft beer irrefutable.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "vivino",
    name: "Vivino",
    icon: "vivino",
    color: "#A61F35",
    authType: "oauth2",
    dataPoints: [
      "vins-notes",
      "cave",
      "wishlist",
      "notes",
      "regions",
    ],
    targetDomains: ["food-lifestyle"],
    targetNiches: ["world-cuisine"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal passionne vin precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "openfoodfacts",
    name: "OpenFoodFacts",
    icon: "openfoodfacts",
    color: "#341100",
    authType: "public",
    apiBaseUrl: "https://world.openfoodfacts.org/api/v2",
    dataPoints: [
      "produits-scannes",
      "contributions",
      "listes",
    ],
    targetDomains: ["food-lifestyle"],
    targetNiches: [
      "nutrition",
      "world-cuisine",
    ],
    signalConfidence: "medium",
    integrationPhase: 4,
    notes:
      "Open source. Signal nutritionnel et consommateur conscient.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "yelp",
    name: "Yelp",
    icon: "yelp",
    color: "#D32323",
    authType: "oauth2",
    apiBaseUrl: "https://api.yelp.com/v3",
    dataPoints: [
      "reviews-postees",
      "categories",
      "check-ins",
    ],
    targetDomains: ["food-lifestyle"],
    targetNiches: [
      "world-cuisine",
      "specialty-coffee",
    ],
    signalConfidence: "medium",
    integrationPhase: 4,
    rateLimitInfo: "500 req/jour",
    notes: "Reviews = signal local et gastronomique.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // CULTURE (4 plateformes uniques — OpenLibrary & Trakt already listed)
  // =========================================================================
  {
    id: "librarything",
    name: "LibraryThing",
    icon: "librarything",
    color: "#251A15",
    authType: "oauth2",
    apiBaseUrl: "https://www.librarything.com/services/rest",
    dataPoints: [
      "catalogue-livres",
      "tags",
      "reviews",
      "groupes",
    ],
    targetDomains: ["literature"],
    targetNiches: [
      "scifi-dystopia",
      "fantasy-epic",
      "book-reviews",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal bibliophile.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "pocket",
    name: "Pocket",
    icon: "pocket",
    color: "#EF4056",
    authType: "oauth2",
    apiBaseUrl: "https://getpocket.com/v3",
    dataPoints: [
      "articles-sauvegardes",
      "tags",
      "domaines-lus",
      "frequence",
    ],
    targetDomains: ["literature", "entrepreneurship"],
    targetNiches: [
      "substack-newsletter",
      "thematic-blog",
      "seo-content",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Tags = interets precis. Domaines = niches reelles.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "feedly",
    name: "Feedly",
    icon: "feedly",
    color: "#2BB24C",
    authType: "oauth2",
    apiBaseUrl: "https://cloud.feedly.com/v3",
    dataPoints: [
      "flux-rss",
      "categories",
      "articles-lus",
      "engagement",
    ],
    targetDomains: ["literature", "entrepreneurship"],
    targetNiches: [
      "thematic-blog",
      "seo-content",
      "data-journalism",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Flux RSS = sources = niches. Signal veille pro.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // NATURE (5 plateformes)
  // =========================================================================
  {
    id: "inaturalist",
    name: "iNaturalist",
    icon: "inaturalist",
    color: "#74AC00",
    authType: "oauth2",
    apiBaseUrl: "https://api.inaturalist.org/v1",
    dataPoints: [
      "observations",
      "especes-identifiees",
      "projets",
    ],
    targetDomains: ["nature-environment", "science"],
    targetNiches: [
      "birdwatching",
      "wildlife-protection",
      "molecular-biology",
    ],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Signal biologiste amateur irrefutable.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "ebird",
    name: "eBird",
    icon: "ebird",
    color: "#4C8C2B",
    authType: "oauth2",
    apiBaseUrl: "https://api.ebird.org/v2",
    dataPoints: [
      "observations-oiseaux",
      "listes",
      "especes",
      "zones",
    ],
    targetDomains: ["nature-environment"],
    targetNiches: ["birdwatching"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "Niche ultra-precise. Signal ornithologiste.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "alltrails",
    name: "AllTrails",
    icon: "alltrails",
    color: "#428813",
    authType: "oauth2",
    dataPoints: [
      "randonnees-completees",
      "photos",
      "reviews",
      "listes",
    ],
    targetDomains: ["nature-environment", "sport-health"],
    targetNiches: [
      "hiking-trek",
      "short-trail",
      "ultra-trail",
    ],
    signalConfidence: "high",
    integrationPhase: 2,
    notes: "Signal outdoor precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "openstreetmap",
    name: "OpenStreetMap",
    icon: "openstreetmap",
    color: "#7EBC6F",
    authType: "oauth2",
    apiBaseUrl: "https://api.openstreetmap.org/api/0.6",
    dataPoints: [
      "contributions-carto",
      "changesets",
      "notes",
    ],
    targetDomains: ["nature-environment"],
    targetNiches: [
      "hiking-trek",
      "oss-contributor",
    ],
    signalConfidence: "medium",
    integrationPhase: 4,
    notes:
      "Contributeur OSM = passionne carto/outdoor/open source.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "wikiloc",
    name: "Wikiloc",
    icon: "wikiloc",
    color: "#60B946",
    authType: "oauth2",
    apiBaseUrl: "https://api.wikiloc.com",
    dataPoints: [
      "traces-gps",
      "trails-partages",
      "sports",
      "zones",
    ],
    targetDomains: ["nature-environment", "sport-health"],
    targetNiches: [
      "hiking-trek",
      "short-trail",
      "cycling-triathlon",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Complement Komoot/Strava pour outdoor.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // NICHE / IRL (3 plateformes)
  // =========================================================================
  {
    id: "meetup",
    name: "Meetup",
    icon: "meetup",
    color: "#F64060",
    authType: "oauth2",
    apiBaseUrl: "https://api.meetup.com",
    dataPoints: [
      "groupes-rejoints",
      "evenements-assistes",
      "categories",
    ],
    targetDomains: [
      "tech-dev",
      "entrepreneurship",
      "performing-arts",
    ],
    targetNiches: [
      "community-building",
      "improv",
      "oss-contributor",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Categories des groupes = interets IRL confirmes.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "eventbrite",
    name: "Eventbrite",
    icon: "eventbrite",
    color: "#F05537",
    authType: "oauth2",
    apiBaseUrl: "https://www.eventbriteapi.com/v3",
    dataPoints: [
      "evenements-crees",
      "billets-achetes",
      "categories",
    ],
    targetDomains: ["entrepreneurship", "performing-arts"],
    targetNiches: [
      "speaking-keynotes",
      "standup",
      "community-building",
    ],
    signalConfidence: "medium",
    integrationPhase: 4,
    notes:
      "Achat billet = validation interet reel.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "letterboxd",
    name: "Letterboxd",
    icon: "letterboxd",
    color: "#00E054",
    authType: "public",
    dataPoints: [
      "films-notes",
      "listes",
      "reviews",
      "genres",
      "realisateurs",
    ],
    targetDomains: ["video-cinema"],
    targetNiches: [
      "arthouse",
      "scifi-fantasy-film",
      "horror-thriller",
      "film-critic",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Pas d'API officielle mais endpoints stables. Signal cinephile top.",
    isPublicApi: true,
    isFreeAccess: true,
  },
]

// =============================================================================
// HELPERS
// =============================================================================

export const PLATFORM_BY_ID = new Map(
  PLATFORM_CATALOG.map((p) => [p.id, p])
)

export function getPlatformsByDomain(
  domainId: string
): PlatformConfig[] {
  return PLATFORM_CATALOG.filter((p) =>
    p.targetDomains.includes(domainId)
  )
}

export function getPlatformsByPhase(
  phase: IntegrationPhase
): PlatformConfig[] {
  return PLATFORM_CATALOG.filter(
    (p) => p.integrationPhase === phase
  )
}

export function getPlatformsByNiche(
  nicheId: string
): PlatformConfig[] {
  return PLATFORM_CATALOG.filter((p) =>
    p.targetNiches.includes(nicheId)
  )
}

export function getFreePlatforms(): PlatformConfig[] {
  return PLATFORM_CATALOG.filter((p) => p.isFreeAccess)
}

export function getPlatformsForOnboarding(
  nicheIds: string[]
): PlatformConfig[] {
  const matched = PLATFORM_CATALOG.filter((p) =>
    p.targetNiches.some((n) => nicheIds.includes(n))
  )
  const confOrder: Record<SignalConfidence, number> = {
    very_high: 0,
    high: 1,
    medium: 2,
    low: 3,
  }
  return matched.sort((a, b) => {
    const confDiff =
      confOrder[a.signalConfidence] -
      confOrder[b.signalConfidence]
    return confDiff !== 0
      ? confDiff
      : a.integrationPhase - b.integrationPhase
  })
}
